version: '3'
services:

  mongodb:
    image: mongo:3.0.4
    command: --smallfiles --master
    ports:
      - "27017:27017"


  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.20.1.RELEASE
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888


  kafka:
    image: eventuateio/eventuateio-local-kafka:0.20.1.RELEASE
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  mysql:
    image: eventuateio/eventuate-tram-sagas-mysql:0.5.0.RELEASE
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw


  tram-cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.9.0.RELEASE
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message

  eventuate-local-cdc-service:
    image: eventuateio/eventuateio-local-cdc-service:0.20.1.RELEASE
    ports:
      - "8098:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH: /eventuatelocal/cdc/leader1

#  customer-service:
#    build: ./customer-service
#    depends_on:
#      - tram-cdc-service
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      JAVA_OPTS: -Xmx192m
#      EUREKA_HOST: eureka-server
## end container
#  api-gateway-service:
#    build: ./api-gateway-service
#    ports:
#      - "8080:8080"
#    environment:
#      CUSTOMER_SERVICE_URL: http://customer-service:8081
#      ACCOUNT_SERVICE_URL: http://account-service:8082
#      MONEY_TRANSFER_SERVICE_URL: http://money-transfer-service:8083
#      CUSTOMER_VIEW_SERVICE_URL: http://customer-view-service:8084
#      ACCOUNT_GROUP_SERVICE_URL: http://account-group-service:8085
#      EUREKA_HOST: eureka-server
## end container
#  account-service:
#    build: ./account-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - tram-cdc-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      JAVA_OPTS: -Xmx192m
#      EUREKA_HOST: eureka-server
## end container
#  money-transfer-service:
#    build: ./money-transfer-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - tram-cdc-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      JAVA_OPTS: -Xmx192m
#      EUREKA_HOST: eureka-server
## end container
#  customer-view-service:
#    build: ./customer-view-service
#    depends_on:
#      - tram-cdc-service
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      SPRING_DATA_MONGODB_URI: mongodb://mongodb/bankingexampledb
#      EUREKA_HOST: eureka-server
## end container
#  account-group-service:
#      build: ./account-group-service
#      depends_on:
#        - eventuate-local-cdc-service
#      ports:
#        - "8085:8085"
#      environment:
#        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#        EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#        EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#        JAVA_OPTS: -Xmx192m
#        EUREKA_HOST: eureka-server
## end container
