apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-service
spec:
  hosts:
  - customer-service
  gateways:
  - banking-example-gateway
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 50
    match:
      - uri:
          prefix: "/api"
    route:
    - destination:
        host: customer-service
        subset: v1
        port:
          number: 8081
    retries:
      attempts: 3
      perTryTimeout: 2s
  - route:
    - destination:
        host: customer-service
        subset: v1
        port:
          number: 8081
---
