apiVersion: v1
kind: Service
metadata:
  name: eventuate-zookeeper
  labels:
    name: eventuate-zookeeper
spec:
  ports:
  - port: 2181
    targetPort: 2181
  clusterIP: None
  selector:
    role: eventuate-zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eventuate-zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        role: eventuate-zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: eventuate-zookeeper
          image: eventuateio/eventuateio-local-zookeeper:0.30.0.M12
          ports:
            - containerPort: 2181
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx192m -Dsun.net.inetaddr.ttl=30"
---
