apiVersion: v1
kind: Service
metadata:
  name: eventuate-kafka
  labels:
    name: eventuate-kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    role: eventuate-kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eventuate-kafka
spec:
  serviceName: "kafka"
  replicas: 1
  template:
    metadata:
      labels:
        role: eventuate-kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: eventuate-kafka
          image: eventuateio/eventuateio-local-kafka:0.30.0.M12
          env:
            - name: KAFKA_HEAP_OPTS
              value: -Xmx320m -Xms320m
            - name: ZOOKEEPER_SERVERS
              value: eventuate-zookeeper:2181
          ports:
              - containerPort: 9092
          volumeMounts:
            - name: eventuate-kafka-config-volume
              mountPath: /usr/local/kafka-config
      volumes:
      - name: eventuate-kafka-config-volume
        configMap:
          name: eventuate-kafka-config
---
